### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ZebrasHaveBigEars** [dwkim78/ASTRiDE#10]
Hi Dae-Won

I spent a day trying to install ASTRiDE on my raspberry pi and have had no success. I am just wondering if it can be updated or installation can be made easier for relative novices like myself.  Thanks!

ZHBE

ps - By the way I am installing on a Raspberry Pi 4 with the new Buster OS

**Comment by dwkim78** [comment]
Hi ZHBE

I'm sorry but I haven't tested ASTRiDE on Rasberry Pi (I even don't possess one).
Hope someone else could help you :)

Cheers,

**Comment by ZebrasHaveBigEars** [comment]
Thanks. Your response is much appreciated. We shall see!

**Comment by ZebrasHaveBigEars** [comment]
Hi there

Just to let people know that the way to install the Raspberry 4 Buster version of ASTRiDE is documented here:
https://github.com/thomasjacquin/allsky/issues/84

Cheers

ZHBE

**Comment by dwkim78** [comment]
Hi,

That looks great! I'll update the ASTRiDE document and include the link as well.

Thanks,

Dae-Won
