### ISSUE TITLE
streak.detect()

### ISSUE THREAD

**Issue by steven-tingay** [dwkim78/ASTRiDE#11]
Hi,

When I use:

ffile='/Users/stingay/NightCap-Photo.fits'
streak = Streak(ffile)
streak.detect()

I get:

File "/Users/stingay/anaconda3/lib/python3.7/site-packages/skimage/measur/_find_contours.py", line 112, in find_contours raise ValueError('Only 2D arrays are supported.')

ValueError: Only 2D arrays are supported.

Do you know what the problem here is?

Regards,
Steven

**Comment by steven-tingay** [comment]
Found the problem.  My FITS image had a third axis (three colours).  Discarding color and creating a BW version fixed the problem.  Is there a way to deal with axis selection in Streak()?
Steven

**Comment by dwkim78** [comment]
Hi,

Could you send me the original fit file (with color) to dwkim78@gmail.com? I'll check what I could do.

Bests,

Dae-Won
