### ISSUE TITLE
Initial and final point of the streak

### ISSUE THREAD

**Issue by fedeaero** [dwkim78/ASTRiDE#13]
Hi,

I didn't understand how I can obtain the coordinates of the initial point and final point of the streak from the .txt file. 
Moreover, once the values are in the .txt file, how can I recover them in python?

Thank you very much.

**Comment by dwkim78** [comment]
Hi,

You can access all the information ASTRIDE provides using the Streak instance. Please check the document: https://github.com/dwkim78/ASTRiDE#accessible-information-inside-the-streak-instance

Cheers,
