### ISSUE TITLE
remove_bkg set to "map"

### ISSUE THREAD

**Issue by shwaylay** [dwkim78/ASTRiDE#14]
Hi,

I am trying to use astride to detect meteors in fits files taken by an All Sky camera. Whenever I try to detect streaks with remove_bkg set to "map," it causes an error no matter what bkg_box_size value I use. It works fine if I use "constant" however.

Thank you for your time.

**Comment by dwkim78** [comment]
Could you give more details (e.g error messages, fits images you used)?

Thanks,

**Comment by shwaylay** [comment]
Yeah, the error message I get is:

  File "C:\...\try_astride_multiple.py", line 115, in do_one
    streak.detect()
  File "C:\...\Python\Python38-32\lib\site-packages\astride\detect.py", line 104, in detect
    self._remove_background()
  File "C:\...\Python\Python38-32\lib\site-packages\astride\detect.py", line 118, in _remove_background
    sigma_clip = SigmaClip(sigma=3., iters=10)
TypeError: __init__() got an unexpected keyword argument 'iters'

and you can find examples of the fits files I am working with on [this website](https://mdallsky.astro.umd.edu/archives/meteor.shtml) from the "link to archives" link.

Thanks again

**Comment by dwkim78** [comment]
I just uploaded new version of ASTRiDE. Please upgrade the package and let me know if it works.

Thanks,

**Comment by shwaylay** [comment]
It works. Thanks!
