### ISSUE TITLE
Blooming

### ISSUE THREAD

**Issue by rankinstudio** [dwkim78/ASTRiDE#15]
Hey, unfortunately blooming makes very long vertical streaks. I can't seem to filter these out even though there is a massive blob in the center of the streak (star). 

I've attached 4 examples, the second one is what I want to extract, You can see the values here: 

#ID x_center y_center area perimeter shape_factor radius_deviation slope_angle intercept connectivity
 1 1632.37  234.75 2806.8  908.6  0.043   0.68 -0.37  246.39 -1
 2 3091.97  291.98  109.7   75.8  0.240   0.54 -51.76 4215.77 -1
 3 4765.65  323.15  596.8  208.5  0.173   0.65 -1.47  445.11 -1
 4 2554.46  326.14  476.8  179.1  0.187   0.64 -1.23  380.91 -1

![1](https://user-images.githubusercontent.com/12660909/110419684-0c314e00-8057-11eb-942e-6c95ca8ebeb1.png)
![2](https://user-images.githubusercontent.com/12660909/110419688-0d627b00-8057-11eb-846a-21b7516f6867.png)
![3](https://user-images.githubusercontent.com/12660909/110419692-0dfb1180-8057-11eb-8484-414ff544b882.png)
![4](https://user-images.githubusercontent.com/12660909/110419694-0dfb1180-8057-11eb-8bd0-309fe7bbb444.png)

The radius deviation should be a variable I could use to remove these, but they have a higher radius deviation than the streak I want so the cut value is cutting the low end.

Settings are:
                        remove_bkg = 'constant',
                        contour_threshold = 10, # contour thresh, high only bright good best 14
                        min_points = 10,  # len in pixels of border
                        shape_cut = 0.25,  # The circularity of a circle is 1, and streak-like shape has much smaller circularity than 1.
                        area_cut = 60,  # area cut, how big is it center of blobs outwards best 1.0
                        radius_dev_cut = 0.5,  # deviation from circular
                        connectivity_angle = 0.1, # for linking streaks

Any suggestion on how I can avoid detecting these bloomed stars and also detect object number 2? Is there any metric that measures the streak width deviation? 

Cheers

David

**Comment by dwkim78** [comment]
If the metrics provided by ASTRiDE fail to distinguish streaks in your data, I suggest you to calculate your own metric using the list of x- and y- coordinates of objects that the ASTRiDE instance (in Python) returns. See https://github.com/dwkim78/ASTRiDE#accessible-information-inside-the-streak-instance

Cheers,

Dae-Won

**Comment by rankinstudio** [comment]
Figured you'd say that. I'll see what I can figure out. 

Cheers
