### ISSUE TITLE
Question about install

### ISSUE THREAD

**Issue by Tanggeshi** [dwkim78/ASTRiDE#17]
When I install ASTRiDE, I meet following error, would you please give me some advice? thank you!   
Using cached scikit-image-0.19.3.tar.gz (22.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [126 lines of output]
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_python_implementation == "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment

**Comment by Tanggeshi** [comment]
Another question is about the Numpy version, would you please give me advice how to modify the numpy setuptools ?

Building wheels for collected packages: scikit-image, pyerfa
  Building wheel for scikit-image (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for scikit-image (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [823 lines of output]
      setup.py:9: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

**Comment by Tanggeshi** [comment]
Do I need to reinstall python 3.11.1 after I install Visual C++ Build Tools for Visual Studio 2015 with Update 3 because I meet the error of " Microsoft Visual C++ 14.0 or greater is required"

**Comment by Tanggeshi** [comment]
Thank you! I had installed ASTRiDE successfully, I had reinstall scikit_learn by download scikit_image-0.19.3-cp311-cp311-win_amd64.whl file, and install it from local disk.

**Comment by dwkim78** [comment]
Good to hear that you figured it out! :)
