### ISSUE TITLE
Why the result of the test example without Ra Dec in streak.txt file?

### ISSUE THREAD

**Issue by Tanggeshi** [dwkim78/ASTRiDE#18]
Hi, I had run astride by test, but why is there no Ra Dec in the streak.txt:

#ID x_center y_center area perimeter shape_factor radius_deviation slope_angle intercept connectivity
 1  260.84  316.66 1077.5  449.8  0.067   0.58 -5.07  339.98  2
 2  105.16  330.27  903.9  428.2  0.062   0.58 -4.93  339.43 -1

**Comment by dwkim78** [comment]
ASTRiDE calculates RA & DEC based on the WCS information of a given fits file. You might want to check the following Python code:

https://github.com/dwkim78/ASTRiDE/blob/7fb7df8f9d0a42f66b71e8af745e4adbd5bdba10/astride/detect.py#L61

**Comment by Tanggeshi** [comment]
I cannot find " wcsinfo = hdulist[0].header["CTYPE1"] " in Python code,  Now I added this code in detect.py and reinstall the ASTRiDE package.  But I cannot get Ra Dec also.  I had check my FITS header, it include the WCS information.

**Comment by Tanggeshi** [comment]
Hi dwKim,
Thank you so much!
I had copy  ASTRiDE/astride/detect.py  to my local disk, and reinstall the package. Now I get Ra Dec correctlly.

**Comment by dwkim78** [comment]
Thanks for letting me know about the issue. I updated the installation document.
