### ISSUE TITLE
Test fail to run

### ISSUE THREAD

**Issue by vkudak** [dwkim78/ASTRiDE#19]
No file with a filename
file_path = '/Users/kim/Downloads/for_dwkim_2022_06_30/fits/'2022_06_29_16_14_01_000_011107-stacked-tn1657066011.fits'

I guess it's your user directory :)
You should put it in the test directory

**Comment by dwkim78** [comment]
Woops, my mistakes :) The test file is already in the test directory. I'll modify the code.
