### ISSUE TITLE
Cannot deteact streak

### ISSUE THREAD

**Issue by vkudak** [dwkim78/ASTRiDE#20]
I experimented with all parameters and still had no chance to detect a relatively bright streak

Here is the link to the FITS file
https://drive.google.com/file/d/1LX6ETBZCarSxdGiVaR7OGi5dz8_hGY1U/view?usp=share_link
![all](https://user-images.githubusercontent.com/6342382/224284560-51815476-11b0-461b-a59d-bd82e67677c5.png)

**Comment by dwkim78** [comment]
That is possible since your streak looks very short, which is hard to detect. You might want to check all the contour lines (accessible from streak.raw_borders), check their properties, and then adjust your parameters.
