### ISSUE TITLE
Additional Streak Data

### ISSUE THREAD

**Issue by michaelbaisch** [dwkim78/ASTRiDE#23]
Hello,

I believe that calculating additional data related to individual streaks would be beneficial for further processing. Initially, I suggest we focus on the thickness, extreme points, and length of the streaks.

I have prepared some code and am currently working on a pull request. I also have specific use cases in mind that could be interesting for this library, which I will detail in a follow-up issues.

Best regards,
Michael

**Comment by dwkim78** [comment]
Hello Michael,

Providing additional data sounds interesting and useful. Let's discuss other issues (that you emailed me) as well after we finish this one.

Bests,
Dae-Won

**Comment by dwkim78** [comment]
- #27 has been merged to the master branch. 
- README.md is updated accordingly.
- ASTRiDE version is updated to 0.3.8
