### ISSUE TITLE
Image resized

### ISSUE THREAD

**Issue by dilukamdp** [dwkim78/ASTRiDE#9]
Hi Kim, thanks for this fantastic software. I have a small concern, I realised that your program resizes the original image and always produce a 1200x900 image ? I wonder whether it is possible to get the streak in the same size ? Many thanks.

**Comment by dwkim78** [comment]
Hi,

It is currently fixed at "detect.py", line number 112. So you might want to adjust it as you want.

Nevertheless, as far as I know, Matplotlib which ASTRiDE uses for plotting doesn't work in pixel but in inches (i.e. physical size) + DPI. So if someone wants to plot in pixel, he/she needs to know DPI of his/her monitor. 

I would more than appreciate if someone could contribute to this issue to improve plotting :)

Thanks.
